[CmdletBinding()]
param(
    [switch]$SkipTests,
    # output folder (default: dist)
    [string]$OutDir
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
# not a param default: $PSScriptRoot is empty there on Windows PowerShell 5.1
if (-not $OutDir) { $OutDir = Join-Path $repoRoot 'dist' }
$project = [System.IO.Path]::Combine($repoRoot, 'NfcTagger.App', 'NfcTagger.App.csproj')
$selfTest = [System.IO.Path]::Combine($repoRoot, 'NfcTagger.SelfTest', 'NfcTagger.SelfTest.csproj')
$readme = Join-Path $repoRoot 'README.md'
$license = Join-Path $repoRoot 'LICENSE'
$licenses = Join-Path $repoRoot 'licenses'
$dist = [System.IO.Path]::GetFullPath($OutDir)
# The SDK cross-publishes Linux from Windows too.
$targets = @(
    @{ Rid = 'win-x64'; Exe = 'NfcTagger.exe' },
    @{ Rid = 'linux-x64'; Exe = 'NfcTagger' }
)

if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    throw '.NET SDK was not found. Install .NET 10 SDK first.'
}
if (-not (Test-Path -LiteralPath $project) -or -not (Test-Path -LiteralPath $selfTest)) {
    throw 'Run this script from a complete NFC Tagger source checkout.'
}

$versionMatch = [regex]::Match([System.IO.File]::ReadAllText($project), '<Version>\s*([^<\s]+)\s*</Version>')
if (-not $versionMatch.Success) { throw 'Version was not found in the app project file.' }
$version = $versionMatch.Groups[1].Value

function Invoke-DotNet {
    param([string[]]$Arguments)
    & dotnet @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw ("dotnet {0} failed with exit code {1}." -f ($Arguments -join ' '), $LASTEXITCODE)
    }
}

Push-Location $repoRoot
try {
    if (-not $SkipTests) {
        Write-Host 'Running NFC Tagger self-tests...'
        Invoke-DotNet -Arguments @('run', '--project', $selfTest, '-c', 'Release')
    }

    New-Item -ItemType Directory -Path $dist -Force | Out-Null
    Add-Type -AssemblyName System.IO.Compression
    Add-Type -AssemblyName System.IO.Compression.FileSystem

    foreach ($target in $targets) {
        $rid = $target.Rid
        $publishDir = Join-Path $dist ("NfcTagger-{0}" -f $rid)
        $marker = Join-Path $publishDir '.nfc-tagger-build-output'
        $zipPath = Join-Path $dist ("NfcTagger-{0}-{1}.zip" -f $version, $rid)

        Write-Host ("Restoring {0} publish dependencies..." -f $rid)
        Invoke-DotNet -Arguments @('restore', $project, '-r', $rid)

        if (Test-Path -LiteralPath $publishDir) {
            $distFull = $dist.TrimEnd([System.IO.Path]::DirectorySeparatorChar)
            $publishFull = [System.IO.Path]::GetFullPath($publishDir)
            if (-not $publishFull.StartsWith($distFull + [System.IO.Path]::DirectorySeparatorChar,
                [System.StringComparison]::OrdinalIgnoreCase)) {
                throw 'Refusing to remove a publish folder outside dist.'
            }
            $item = Get-Item -LiteralPath $publishDir
            if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
                throw 'Refusing to remove a linked publish folder.'
            }
            if (-not (Test-Path -LiteralPath $marker)) {
                throw 'Existing publish folder has no NFC Tagger build marker; refusing to overwrite it.'
            }
            Remove-Item -LiteralPath $publishDir -Recurse -Force
        }

        Write-Host ("Publishing self-contained {0} app..." -f $rid)
        Invoke-DotNet -Arguments @('publish', $project, '-c', 'Release', '-r', $rid,
            '--self-contained', 'true', '--no-restore', '-o', $publishDir)
        $exe = Join-Path $publishDir $target.Exe
        if (-not (Test-Path -LiteralPath $exe)) { throw ("Publish completed without {0}." -f $target.Exe) }

        Copy-Item -LiteralPath $readme -Destination (Join-Path $publishDir 'README.md')
        Copy-Item -LiteralPath $license -Destination (Join-Path $publishDir 'LICENSE')
        Copy-Item -LiteralPath $licenses -Destination (Join-Path $publishDir 'licenses') -Recurse
        Set-Content -LiteralPath $marker -Value 'Generated by build.ps1' -Encoding Ascii

        Write-Host ("Creating {0} ZIP..." -f $rid)
        # Windows PowerShell 5.1's Compress-Archive writes '\' separators, so build entries with '/' explicitly.
        # A zip made on Windows has no Unix execute bit, so the README tells Linux users to chmod +x.
        if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
        $publishFull = [System.IO.Path]::GetFullPath($publishDir).TrimEnd([System.IO.Path]::DirectorySeparatorChar)
        $baseName = Split-Path -Leaf $publishFull
        $writer = [System.IO.Compression.ZipFile]::Open($zipPath, [System.IO.Compression.ZipArchiveMode]::Create)
        try {
            foreach ($file in Get-ChildItem -LiteralPath $publishFull -Recurse -File -Force) {
                $relative = $file.FullName.Substring($publishFull.Length + 1).Replace('\', '/')
                [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($writer, $file.FullName,
                    "$baseName/$relative", [System.IO.Compression.CompressionLevel]::Optimal) | Out-Null
            }
        }
        finally { $writer.Dispose() }
        $archive = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
        try {
            $names = @($archive.Entries | ForEach-Object { $_.FullName })
            foreach ($expected in @("$baseName/$($target.Exe)",
                "$baseName/README.md",
                "$baseName/LICENSE",
                "$baseName/licenses/PCSC-COPYING.txt",
                "$baseName/licenses/Avalonia-LICENSE.txt",
                "$baseName/licenses/System.IO.Ports-THIRD-PARTY-NOTICES.txt")) {
                if ($names -notcontains $expected) {
                    throw ("The {0} ZIP is missing {1}." -f $rid, $expected)
                }
            }
        }
        finally { $archive.Dispose() }

        $hash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash
        Write-Host ("{0} EXE: {1}" -f $rid, $exe)
        Write-Host ("{0} ZIP: {1}" -f $rid, $zipPath)
        Write-Host ("{0} SHA256: {1}" -f $rid, $hash)
    }
}
finally {
    Pop-Location
}
