[CmdletBinding()]
param(
    [switch]$SkipTests
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$project = Join-Path $repoRoot 'NfcTagger.App\NfcTagger.App.csproj'
$selfTest = Join-Path $repoRoot 'NfcTagger.SelfTest\NfcTagger.SelfTest.csproj'
$readme = Join-Path $repoRoot 'README.md'
$licenses = Join-Path $repoRoot 'licenses'
$dist = Join-Path $repoRoot 'dist'
$publishDir = Join-Path $dist 'NfcTagger-win-x64'
$marker = Join-Path $publishDir '.nfc-tagger-build-output'

if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    throw '.NET SDK was not found. Install .NET 10 SDK first.'
}
if (-not (Test-Path -LiteralPath $project) -or -not (Test-Path -LiteralPath $selfTest)) {
    throw 'Run this script from a complete NFC Tagger source checkout.'
}

$versionMatch = [regex]::Match([System.IO.File]::ReadAllText($project), '<Version>\s*([^<\s]+)\s*</Version>')
if (-not $versionMatch.Success) { throw 'Version was not found in the WPF project file.' }
$version = $versionMatch.Groups[1].Value
$zipPath = Join-Path $dist ("NfcTagger-{0}-win-x64.zip" -f $version)

function Invoke-DotNet {
    param([string[]]$Arguments)
    & dotnet @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw ("dotnet {0} failed with exit code {1}." -f ($Arguments -join ' '), $LASTEXITCODE)
    }
}

Push-Location $repoRoot
try {
    if (-not $SkipTests) {
        Write-Host 'Running NFC Tagger self-tests...'
        Invoke-DotNet -Arguments @('run', '--project', $selfTest, '-c', 'Release')
    }

    Write-Host 'Restoring Windows x64 publish dependencies...'
    Invoke-DotNet -Arguments @('restore', $project, '-r', 'win-x64')

    New-Item -ItemType Directory -Path $dist -Force | Out-Null
    if (Test-Path -LiteralPath $publishDir) {
        $distFull = [System.IO.Path]::GetFullPath($dist).TrimEnd([System.IO.Path]::DirectorySeparatorChar)
        $publishFull = [System.IO.Path]::GetFullPath($publishDir)
        if (-not $publishFull.StartsWith($distFull + [System.IO.Path]::DirectorySeparatorChar,
            [System.StringComparison]::OrdinalIgnoreCase)) {
            throw 'Refusing to remove a publish folder outside dist.'
        }
        $item = Get-Item -LiteralPath $publishDir
        if (($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
            throw 'Refusing to remove a linked publish folder.'
        }
        if (-not (Test-Path -LiteralPath $marker)) {
            throw 'Existing publish folder has no NFC Tagger build marker; refusing to overwrite it.'
        }
        Remove-Item -LiteralPath $publishDir -Recurse -Force
    }

    Write-Host 'Publishing self-contained Windows x64 app...'
    Invoke-DotNet -Arguments @('publish', $project, '-c', 'Release', '-r', 'win-x64',
        '--self-contained', 'true', '--no-restore', '-o', $publishDir)
    $exe = Join-Path $publishDir 'NfcTagger.exe'
    if (-not (Test-Path -LiteralPath $exe)) { throw 'Publish completed without NfcTagger.exe.' }

    Copy-Item -LiteralPath $readme -Destination (Join-Path $publishDir 'README.md')
    Copy-Item -LiteralPath $licenses -Destination (Join-Path $publishDir 'licenses') -Recurse
    Set-Content -LiteralPath $marker -Value 'Generated by build.ps1' -Encoding Ascii

    Write-Host 'Creating portable ZIP...'
    Compress-Archive -Path $publishDir -DestinationPath $zipPath -CompressionLevel Optimal -Force
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $archive = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
    try {
        $names = @($archive.Entries | ForEach-Object { $_.FullName })
        foreach ($expected in @('NfcTagger-win-x64/NfcTagger.exe',
            'NfcTagger-win-x64/README.md',
            'NfcTagger-win-x64/licenses/PCSC-COPYING.txt',
            'NfcTagger-win-x64/licenses/System.IO.Ports-THIRD-PARTY-NOTICES.txt')) {
            if ($names -notcontains $expected) {
                throw ("The portable ZIP is missing {0}." -f $expected)
            }
        }
    }
    finally { $archive.Dispose() }

    $hash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash
    Write-Host ("EXE: {0}" -f $exe)
    Write-Host ("ZIP: {0}" -f $zipPath)
    Write-Host ("SHA256: {0}" -f $hash)
}
finally {
    Pop-Location
}
